version: "3.8"

# Docker Compose configuration to build and run the Postgres database service
services:
  database:
    build:
      context: ./Postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

# Docker Compose configuration to build and run the backend service
  backend:
    build:
      context: ./Java
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd
    ports:
      - "8080:8080"
    networks:
      - app-network

# Docker Compose configuration to build and run the HTTP server service
  http_server:
    build:
      context: ./HTTP
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

# Docker Compose configuration to run the Adminer database management UI
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8888:8080"
    depends_on:
      - database
    networks:
      - app-network

# Docker Compose configuration for the custom network and data volume
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: