- hosts: all
  gather_facts: true
  become: true

  roles:
    - docker
    - createnetwork
    - launchdatabase
    - launchapp
    - launchproxy

# We just call here the roles we created in the roles directory.
# Each role will have its own tasks, handlers, and variables defined in their respective directories.
# This playbook will run on all hosts defined in the inventory file.
# The roles will be executed in the order they are listed.
# Make sure to have the necessary inventory file and roles directory structure set up.
# You can run this playbook using the command:
# ansible-playbook -i inventory playbook.yml
# Tou have the definition of each role in a ReadME.md file in the roles directory.
# Ensure you have the necessary permissions and configurations set up in your Ansible environment.