# .github/workflows/main.yml
name: CI devops 2025

on:
  # Déclencher sur un push dans les branches main ou develop
  push:
    branches:
      - main
      - develop

  # Déclencher également sur Pull Request via ces mêmes branches
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      # 1) Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Installer le JDK 19
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'       # ou 'zulu', 'adopt', etc. selon vos préférences
          cache: 'maven'                # met en cache le répertoire ~/.m2 pour accélérer les builds

      # 3) Afficher la version de Java (debug, optionnel)
      - name: Check Java version
        run: java -version

      # 4) Compiler, tester et vérifier avec Maven
      - name: Build and test with Maven
+       working-directory: Java   # ← indiquez ici le chemin vers votre dossier contenant le pom.xml
+       run: mvn clean verify